{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Bjelijah",
    "module": "Translation",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "5enbd7kb3jgafhfgiva4rzfyfi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Translation-1.1.5.jar",
          "url": "Translation-1.1.5.jar",
          "size": 24175,
          "sha512": "4cd5421e0e0ec5a1bde3c12b4be1b456a5b478aab449483584f59e7b4f3509d0d1bf965884aba6d4d45f98cb3a98f2e8e9a1ebf7e54cc15961d1d4bf3359a645",
          "sha256": "64a43c9950ac4357ceefe969414b070ddc587ef631a2e56e10bf38d6586a2fc4",
          "sha1": "1ec1bd21fcbad66f66d8a0fe45c3a96ff8ba4cdd",
          "md5": "33926e84da3baf397628e64ee0bff2c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "Translation-1.1.5.jar",
          "url": "Translation-1.1.5.jar",
          "size": 24175,
          "sha512": "4cd5421e0e0ec5a1bde3c12b4be1b456a5b478aab449483584f59e7b4f3509d0d1bf965884aba6d4d45f98cb3a98f2e8e9a1ebf7e54cc15961d1d4bf3359a645",
          "sha256": "64a43c9950ac4357ceefe969414b070ddc587ef631a2e56e10bf38d6586a2fc4",
          "sha1": "1ec1bd21fcbad66f66d8a0fe45c3a96ff8ba4cdd",
          "md5": "33926e84da3baf397628e64ee0bff2c6"
        }
      ]
    }
  ]
}
